MODEL:
  TYPE: "ADVIR"
  EMBEDDING_SIZE: 64
  REGSD: 1e-5
  REGSG: 1e-5
DATASET:
  ROOT_DIR: "data/yelp2018/"
  SAMPLING: "RANDOM_SAMPLE"
  K_NEGS: 8
DATALOADER:
  NUM_WORKERS: 4
SOLVER:
  TYPEG: "Adam"
  BASE_LRG: 0.001
  TYPED: "Adam"
  BASE_LRD: 0.001
TRAIN:
  BATCH_SIZE: 1024
  LOG_PERIOD: 1
  TYPE: "GAN"
  EARLY_STOP: 8
TEST:
  METRIC: "RECALL"
