MODEL:
  TYPE: "BPR-MF"
  EMBEDDING_SIZE: 64
  REGS: 1e-5
DATASET:
  ROOT_DIR: "data/yelp2018/"
  SAMPLING: "POPULA"
  K_NEGS: 1
DATALOADER:
  NUM_WORKERS: 8
SOLVER:
  TYPE: "Adam"
  BASE_LR: 0.0001
TRAIN:
  BATCH_SIZE: 1024
  LOG_PERIOD: 1
  TYPE: "MF"
  EARLY_STOP: 8
TEST:
  METRIC: "RECALL"
