MODEL:
  TYPE: "DNS"
  EMBEDDING_SIZE: 64
  REGS: 1e-5
DATASET:
  ROOT_DIR: "data/amazon-book/"
  SAMPLING: "RANDOM_SAMPLE"
  K_NEGS: 8
DATALOADER:
  NUM_WORKERS: 4
SOLVER:
  TYPE: "Adam"
  BASE_LR: 0.001
TRAIN:
  BATCH_SIZE: 1024
  LOG_PERIOD: 1
  TYPE: "MF"
  EARLY_STOP: 12
TEST:
  METRIC: "RECALL"